### PR TITLE
fix: embed reference block

### LINKED ISSUE #21: Support for block references?
Hi, thanks for the wonderful plugin!

I was wondering if it can also support tasks that come from block references / block embeds. What I like to do is to note tasks in my daily notes and then reference them in a project note, but the way the todo-master plugin works now doesn't allow for that. 

Many thanks!

### PR DESCRIPTION
**Pull request by 3attaE**
Fixes #21 

support Logseq embed block 

add `getReferenceContent` function to get reference real content uuid

```
- <todo-master>
  - {{embed (())}}
```

image

### CODE REVIEW

File: src/register-command.tsx [hunk 1]
```diff
@@ -153,6 +153,22 @@ async function getBlockTreeAndMode(maybeUUID: string) {
   return { tree, mode };
 }
 
+function getReferenceContent(content: string): string | null {
```
Comment (pengx17) [inline src/register-command.tsx:156]: Not sure if you want to also consider cases that there are multiple block references been embedded. Also, I think you can simplify the logic with a regex like this one:
`content.matchAll(/\(\(([a-zA-Z0-9-]*)\)\)/g))`, which returns all the matched block ref ids

Comment (3attaE) [reply src/register-command.tsx:156]: ok, I modify it after.

**Review by pengx17 — APPROVED** [review]
LGTM, thank you!
